### ISSUE TITLE
Full Page Cache corrupts javascript containing html

### ISSUE THREAD

**Issue by Ezyweb-uk** [microweber/microweber#594]
The Full Page Cache considerably improves page load time at GTMetrix.com and is therefore a valuable tool. However I've noticed an issue twice where the caching corrupts javascript that contains html content. For example with the video module when a video is uploaded and a thumbnail is used the video lazyloading script contains html, and the full page cache causes a closing script tag to be inserted at the wrong place as seen below (tested with 1.1.8 dev).

![video-full-page-cache](https://user-images.githubusercontent.com/7723418/62360125-1781d680-b510-11e9-9158-08147030394d.jpg)

This results in the line of code `';img.parentNode.replaceChild(div, img);} `  showing above the video. The same code works fine with Eull Page Cache off. The work-around I found was to urlencode the script and then decode it via an ajax call, but maybe there's an easier fix?

This behaviour also occurs if I try to add a modal form to eg the user's profile page in the website. For example:
`		mw_modname_popup_modal_opened = mw.modal({
			content:   '<div id="mw_edit_modname_module"></div>',
			title:     modalTitle,
			width: 	   400,
			height:	   400,
			id:        'mw_modname_popup_modal'
		});`
The html in the 'content' parameter causes a closing script tag to be added in the wrong place and corrupts the javascript. It would be great if the Full Page Cache could work with this construct, it doesn't seem to cause an issue with modals in admin.

**Comment by peter-mw** [comment]
hi Nick, thanks for report, this is still experimental feature and it needs more work , we will try to fix it soon

**Comment by Ezyweb-uk** [comment]
Thanks Peter. This experimental feature looks very worthwhile for page load times and therefore SEO.

I tried setting `$config['no_cache'] = true;` in the video module config.php but that didn't work (maybe only for asset caching). I notice that adding any url parameter to a page url to populate `$_GET` does switch off the Full Page Cache for a specific page.

I see that in DefaultController.php that the status of the following variables control the Full Page Cache: `$back_to_editmode`,`$is_editmode` ,`$_GET` and `$enable_full_page_cache`. Hopefully the caching can be made to work with html content within javascript, otherwise it would be good if caching could some how be disabled for a specific module or a specific page.

**Comment by peter-mw** [comment]
hi nick, can you pull from dev branch and test again? 
i just tested and its working here, we fixed a bug with scripts replacing in dev branch which may be related

**Comment by Ezyweb-uk** [comment]
Hi Peter, I've updated my dev copy, cleared the cache and reloaded the database in admin > settings, but with Full Page Cache on, if I set a video to use a thumbnail (for lazyloading) it still shows some javascript above it as seen below.

![full-page-cache-with-html-in-js](https://user-images.githubusercontent.com/7723418/62611523-aec69f80-b8fd-11e9-98ce-338689a41845.jpg)

With FPC off it's ok

**Comment by Ezyweb-uk** [comment]
The experimental Full Page Cache seems to work nicely with the latest video module, and on initial testing seems to cut page loading time by as much as 38% and header size by 45% according to GTmetrix. 

However the other experimental caching option 'optimize asset loading' seemed to screw-up the css layout both for the website and admin. But is 'optimize asset loading' needed if the 'Full Page Cache' is working?
