### ISSUE TITLE
Class 'JsonMachine\JsonMachine' not found

### ISSUE THREAD

**Issue by majidalavizadeh** [microweber/microweber#794]
I'm gonna install a fresh version of Microweber via Composer.
Installing the required packages with `composer install`, as well as serving Laravel via `php artisan serve`, is what I do.

When I try to install Microweber on my first visit on `http://localhost:8000` I receive a `500 Internal Server Error` and when I check the `laravel.log` it states this:

```
production.ERROR: Class 'JsonMachine\JsonMachine' not found
```

Does anyone else have this problem and know what the issue is?

**Comment by aalsamman** [comment]
I confirm having the same exact issue. I have tried on multiple machines with different php versions and the error persists.

**Comment by bojo123** [comment]
yes having the same exact issue

**Comment by tr-shishir** [comment]
Yes, Please use this plug in **composer require droptienda/json-machine**
That will solve your problem

**Comment by majidalavizadeh** [comment]
Thank you for the solution, the installation has passed. but new problems occurred.

Installation does not seem to be successful because I get this page after installation:
![image](https://user-images.githubusercontent.com/1640821/152523010-bb84bf75-548c-42b3-a138-942cad9f0286.png)

And on the installation page I can see these errors in the console:
![image](https://user-images.githubusercontent.com/1640821/152522934-a6bdb7a5-e3bf-4bd5-9bd7-4f873a9cad0d.png)

And when I enter `/admin`, I get this page and I have to refresh the page to see the admin panel.
![image](https://user-images.githubusercontent.com/1640821/152523102-5eb210af-cee1-4193-aae7-9eb9c453b61d.png)

Also, nothing works in the admin panel, I get this error in the browser console.
![image](https://user-images.githubusercontent.com/1640821/152521993-e14be8fc-bb50-4028-9d66-9cfe16381ded.png)


Do you know what is the problem?

**Comment by peter-mw** [comment]
hi, we have fixed this problem in the [dev](https://github.com/microweber/microweber/tree/dev) branch, and will release update soon

**Comment by majidalavizadeh** [comment]
Thank you @peter-mw, I tested on the [dev](https://github.com/microweber/microweber/tree/dev) branch and the problem still exists. (version is 1.2.11)

**Comment by peter-mw** [comment]
fixed
