### ISSUE TITLE
Pages from disabled languages are still accessible by visitor

### ISSUE THREAD

**Issue by RogerAntonio** [microweber/microweber#860]
My language settings:
![image](https://user-images.githubusercontent.com/5510591/167224238-9ad1a747-35ec-4d57-896a-00da7522f225.png)

For some reason I got a report from a friend that my website content wasn't there.
He said he just went to my website https://weblama.be
The reason my content wasn't there was because for some reason he was on the American English version of my website.
Eventhough that language is disabled.
All I can think of is that this might be because of it being the default language?
But I can't seem to find a way to change the default language.
There also is no fall-back for pages on disabled languages. 
It should redirect to the enabled language(s).

**Comment by peter-mw** [comment]
Thanks for report, we fixed it in the `dev` branch

**Comment by RogerAntonio** [comment]
The issue persists on the latest dev branch (updated with the Standalone updater).
Visitors can still access American English (Default) while it's disabled.
Visitors still don't get redirected to enabled language(s).
![image](https://user-images.githubusercontent.com/5510591/167933585-34f15734-a32d-4300-a3f8-0ac2bd05ffee.png)

Settings again:
![image](https://user-images.githubusercontent.com/5510591/167933605-f2c856d5-6580-4212-95a8-fe91fe603f43.png)

The visitor who reported the issue said they got to these pages through Google Results.
I can't reproduce this, but I am able to access the pages as well in an incognito window.

**Comment by RogerAntonio** [comment]
@bobimicroweber I don't know how to reopen this issue.
